version: '3.8'

services:
  backend:
    image: python:3.10
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install uv && pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
 
